### ISSUE TITLE
Thanks for this, send 250 response

### ISSUE THREAD

**Issue by deankarn** [andrewarrow/jungle_smtp#1]
Thanks for this, helped me in writing some tests

you may want to add `c.w("250 server has transmitted the message")` after [this](https://github.com/andrewarrow/jungle_smtp/blob/master/main.go#L60) line just in case the server is not expecting the connection to close like my code was doing.

And agian, thanks again 👍

**Comment by andrewarrow** [comment]
Good call! I added the line. Welcome to the jungle joeybloggs!
